[package]
name = "example-shared-lib"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
bevy = { optional = true, workspace = true }
es-fluent = { features = [ "derive", "generate" ], workspace = true }
es-fluent-lang = { workspace = true }
es-fluent-manager-bevy = { optional = true, workspace = true }
es-fluent-manager-embedded = { optional = true, workspace = true }
gpui = { optional = true, workspace = true }
rust-embed = { optional = true, workspace = true }
strum = { features = [ "derive" ], workspace = true }

[lints]
workspace = true

[features]
bevy = [ "dep:bevy", "dep:es-fluent-manager-bevy", "es-fluent-lang/bevy" ]
embedded = [ "dep:rust-embed", "dep:es-fluent-manager-embedded" ]
gpui = [ "dep:gpui", "dep:rust-embed", "dep:es-fluent-manager-embedded" ]
