[workspace]
members = [
  "crates/es-fluent",
  "crates/es-fluent-cli",
  "crates/es-fluent-cli-helpers",
  "crates/es-fluent-derive-core",
  "crates/es-fluent-toml",
  "crates/es-fluent-derive",
  "crates/es-fluent-generate",
  "crates/es-fluent-lang",
  "crates/es-fluent-lang-macro",
  "crates/es-fluent-manager-core",
  "crates/es-fluent-manager-macros",
  "crates/es-fluent-manager-embedded",
  "crates/es-fluent-manager-bevy",
  "examples/first-example",
  "examples/thiserror-example",
  "examples/example-shared-lib",
  "examples/feature-gated-example",
  "examples/bevy-example",
  "examples/gpui-example",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/es-fluent"
rust-version = "1.88"
version = "0.6.0"

[workspace.dependencies]
anyhow = "1.0.98"
arc-swap = "1.7.1"
askama = "0.15.0"
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
bevy = "0.18.0"
blake3 = "1.8.2"
bon = "3.3.2"
cargo_metadata = "0.23"
chrono = "0.4.42"
clap = "4.5.38"
colored = "3.0.0"
crossterm = "0.29.0"
darling = "0.23.0"
derive_more = "2.0.1"
es-fluent = { path = "crates/es-fluent", version = "0.6.0" }
es-fluent-derive = { path = "crates/es-fluent-derive", version = "0.6.0" }
es-fluent-derive-core = { path = "crates/es-fluent-derive-core", version = "0.6.0" }
es-fluent-generate = { path = "crates/es-fluent-generate", version = "0.6.0" }
es-fluent-lang = { path = "crates/es-fluent-lang", version = "0.6.0" }
es-fluent-lang-macro = { path = "crates/es-fluent-lang-macro", version = "0.6.0" }
es-fluent-manager-bevy = { path = "crates/es-fluent-manager-bevy", version = "0.18.0" }
es-fluent-manager-core = { path = "crates/es-fluent-manager-core", version = "0.6.0" }
es-fluent-manager-embedded = { path = "crates/es-fluent-manager-embedded", version = "0.6.0" }
es-fluent-manager-macros = { path = "crates/es-fluent-manager-macros", version = "0.6.0" }
es-fluent-toml = { path = "crates/es-fluent-toml", version = "0.6.0" }
fluent-bundle = "0.16.0"
fluent-syntax = "0.12"
getset = "0.1.3"
glob = "0.3.3"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
heck = "0.5.0"
humantime = "2.2.0"
indicatif = "0.18.3"
insta = { version = "1.43.2" }
intl-memoizer = "0.5.3"
inventory = "0.3.20"
miette = "7.6.0"
notify = "8.2"
notify-debouncer-full = "0.6.0"
predicates = "3.1.3"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0.92"
quote = "1.0.38"
ratatui = "0.30.0"
rayon = "1.10.0"
regex = "1.12.2"
rust-embed = "8.5.0"
rust_decimal = "1.39.0"
serde = "1.0.217"
serde_json = "1.0"
similar = "2.7.0"
strum = "0.27.2"
syn = "2.0.92"
tempfile = "3.23.0"
terminal-link = "0.1.0"
thiserror = "2.0.12"
throbber-widgets-tui = "0.10.0"
toml = "0.9.5"
tracing = "0.1.44"
unic-langid = "0.9.6"
walkdir = "2.5.0"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"
