[workspace]
members = [
  "crates/es-fluent",
  "crates/es-fluent-core",
  "crates/es-fluent-toml",
  "crates/es-fluent-derive",
  "crates/es-fluent-build",
  "crates/es-fluent-generate",
  "crates/es-fluent-sc-parser",
  "crates/es-fluent-cli",
  "crates/es-fluent-lang",
  "crates/es-fluent-lang-macro",
  "crates/es-fluent-manager-core",
  "crates/es-fluent-manager-macros",
  "crates/es-fluent-manager-embedded",
  "crates/es-fluent-manager-bevy",
  "examples/first-example",
  "examples/thiserror-example",
  "examples/example-shared-lib",
  "examples/bevy-example",
  "examples/gpui-example",
  "examples/iced-example",
  "examples/cosmic-example",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/es-fluent"
rust-version = "1.88"
version = "0.2.11"

[workspace.dependencies]
anyhow = "1.0.98"
bevy = "0.17.0"
bon = "3.3.2"
borrow = "1.3.0"
cargo_metadata = "0.23"
clap = "4.5.38"
colored = "3.0.0"
crate-paths = "0.1.1"
crossterm = "0.29.0"
darling = "0.21.3"
derive_more = "2.0.1"
env_logger = "0.11"
es-fluent = { default-features = false, path = "crates/es-fluent", version = "0.2.11" }
es-fluent-build = { path = "crates/es-fluent-build", version = "0.2.11" }
es-fluent-core = { default-features = false, path = "crates/es-fluent-core", version = "0.2.11" }
es-fluent-derive = { path = "crates/es-fluent-derive", version = "0.2.11" }
es-fluent-generate = { path = "crates/es-fluent-generate", version = "0.2.11" }
es-fluent-lang = { path = "crates/es-fluent-lang", version = "0.2.11" }
es-fluent-lang-macro = { path = "crates/es-fluent-lang-macro", version = "0.2.11" }
es-fluent-manager-bevy = { path = "crates/es-fluent-manager-bevy", version = "0.17.11" }
es-fluent-manager-core = { path = "crates/es-fluent-manager-core", version = "0.2.11" }
es-fluent-manager-embedded = { path = "crates/es-fluent-manager-embedded", version = "0.2.11" }
es-fluent-manager-macros = { path = "crates/es-fluent-manager-macros", version = "0.2.11" }
es-fluent-sc-parser = { path = "crates/es-fluent-sc-parser", version = "0.2.11" }
es-fluent-toml = { path = "crates/es-fluent-toml", version = "0.2.11" }
fluent = { version = "0.17.0" }
fluent-bundle = "0.16.0"
fluent-syntax = "0.12"
garde = "0.22.0"
getset = "0.1.3"
gpui = "0.2.0"
gpui-component = "0.3.1"
heck = "0.5.0"
humantime = "2.2.0"
iced = { default-features = false, version = "0.13.1" }
insta = { features = [ "json" ], version = "1.43.2" }
intl-memoizer = "0.5.3"
inventory = "0.3.20"
itertools = "0.14.0"
log = "0.4"
notify = "8.2"
paste = "1.0.15"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0.92"
quote = "1.0.38"
ratatui = "0.29.0"
rayon = "1.10.0"
rust-embed = "8.5.0"
serde = "1.0.217"
state-shift = "2.1.1"
strum = "0.27.2"
syn = "2.0.92"
tempfile = "3.23.0"
thiserror = "2.0.12"
tokio = "1.45.1"
toml = "0.9.5"
tracing = "0.1"
unic-langid = "0.9.6"
walkdir = "2.5.0"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"
