[workspace]
members = [
  "crates/es-fluent",
  "crates/es-fluent-cli",
  "crates/es-fluent-cli-helpers",
  "crates/es-fluent-derive-core",
  "crates/es-fluent-toml",
  "crates/es-fluent-derive",
  "crates/es-fluent-generate",
  "crates/es-fluent-lang",
  "crates/es-fluent-lang-macro",
  "crates/es-fluent-manager-core",
  "crates/es-fluent-manager-macros",
  "crates/es-fluent-manager-embedded",
  "crates/es-fluent-manager-bevy",
  "examples/first-example",
  "examples/thiserror-example",
  "examples/example-shared-lib",
  "examples/feature-gated-example",
  "examples/bevy-example",
  "examples/gpui-example",
  "examples/readme",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/es-fluent"
rust-version = "1.88"
version = "0.9.0"

[workspace.dependencies]
anyhow = "1.0"
arc-swap = "1.8"
askama = "0.15"
assert_cmd = "2.1"
assert_fs = "1.1"
bevy = "0.18"
blake3 = "1.8"
bon = "3.8"
cargo_metadata = "0.23"
chrono = "0.4"
clap = "4.5"
colored = "3.0"
crossterm = "0.29"
darling = "0.23"
derive_more = "2.1"
es-fluent = { path = "crates/es-fluent", version = "0.9.0" }
es-fluent-derive = { path = "crates/es-fluent-derive", version = "0.9.0" }
es-fluent-derive-core = { path = "crates/es-fluent-derive-core", version = "0.9.0" }
es-fluent-generate = { path = "crates/es-fluent-generate", version = "0.9.0" }
es-fluent-lang = { path = "crates/es-fluent-lang", version = "0.9.0" }
es-fluent-lang-macro = { path = "crates/es-fluent-lang-macro", version = "0.9.0" }
es-fluent-manager-bevy = { default-features = false, path = "crates/es-fluent-manager-bevy", version = "0.18.3" }
es-fluent-manager-core = { path = "crates/es-fluent-manager-core", version = "0.9.0" }
es-fluent-manager-embedded = { path = "crates/es-fluent-manager-embedded", version = "0.9.0" }
es-fluent-manager-macros = { path = "crates/es-fluent-manager-macros", version = "0.9.0" }
es-fluent-toml = { path = "crates/es-fluent-toml", version = "0.9.0" }
fluent-bundle = "0.16"
fluent-fallback = "0.7"
fluent-syntax = "0.12"
getset = "0.1"
glob = "0.3"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
heck = "0.5"
humantime = "2.3"
indexmap = "2.13"
indicatif = "0.18"
insta = { version = "1.46" }
intl-memoizer = "0.5"
inventory = "0.3"
miette = "7.6"
notify = "8.2"
notify-debouncer-full = "0.6"
predicates = "3.1"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
ratatui = "0.30"
rayon = "1.11"
regex = "1.12"
rust-embed = "8.11"
rust_decimal = "1.40"
serde = "1.0"
serde_json = "1.0"
similar = "2.7"
strum = "0.27"
syn = "2.0"
tempfile = "3.24"
terminal-link = "0.1"
thiserror = "2.0"
throbber-widgets-tui = "0.10"
toml = "0.9"
tracing = "0.1"
unic-langid = "0.9"
walkdir = "2.5"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"
