[package]
name = "bevy-example"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
bevy = { features = [ "wayland", "file_watcher" ], workspace = true }
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-bevy = { workspace = true }
example-shared-lib = { features = [ "bevy" ], path = "../example-shared-lib" }
unic-langid = { workspace = true }

[lints]
workspace = true
