[package]
name = "gpui-example"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
example-shared-lib = { features = [ "gpui" ], path = "../example-shared-lib" }
gpui = { workspace = true }
gpui-component = { workspace = true }
rust-embed = { workspace = true }
unic-langid = { workspace = true }

[build-dependencies]
es-fluent = { features = [ "build" ], workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [ "rust-embed" ]
