[package]
name = "thiserror-example"
version = "0.1.0"
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { features = [ "derive", "generate" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
example-shared-lib = { features = [ "embedded" ], path = "../example-shared-lib" }
rust-embed = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
thiserror = { workspace = true }
unic-langid = { workspace = true }

[lints]
workspace = true
