[package]
name = "es-fluent"
description = """
The es-fluent crate
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
categories = [ "localization", "internationalization", "development-tools::build-utils" ]
keywords = [ "fluent", "i18n", "locale" ]
license.workspace = true
publish.workspace = true
repository.workspace = true
readme.workspace = true

[features]
cli = [ "dep:serde", "dep:serde_json" ]
default = [ "derive" ]
derive = [ "dep:es-fluent-derive" ]

[dependencies]
es-fluent-core = { workspace = true }
es-fluent-derive = { optional = true, workspace = true }
es-fluent-manager-core = { workspace = true }
fluent-bundle = { workspace = true }
inventory = { workspace = true }
rust-embed = { workspace = true }
serde = { features = [ "derive" ], optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
tracing = { workspace = true }
unic-langid = { features = [ "macros" ], workspace = true }

[dev-dependencies]
chrono = { workspace = true }
es-fluent-generate = { workspace = true }
rust_decimal = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
