[package]
name = "feature-gated-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
es-fluent = { features = [ "derive" ], optional = true, workspace = true }

[build-dependencies]
es-fluent = { features = [ "build" ], workspace = true }

[features]
default = [  ]
fluent = [ "dep:es-fluent" ]
