[package]
name = "es-fluent-cli"
description = "CLI for es-fluent FTL file generation"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "es-fluent"
path = "src/main.rs"

[dependencies]
askama = { workspace = true }
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { features = ["derive"], workspace = true }
colored = { workspace = true }
crossterm = { workspace = true }
ctrlc = "3.4"
es-fluent-toml = { workspace = true }
humantime = { workspace = true }
notify = "7"
notify-debouncer-mini = "0.5"
ratatui = { features = ["crossterm"], workspace = true }
walkdir = "2"

[dev-dependencies]
tempfile = { workspace = true }


[lints]
workspace = true
